```{r}
#Install and Load RCurl Package
library(curl)
library(tidyverse)
library(readr)
library(dplyr)
library(lubridate)
```


I'll work on cleaning the GAMES dataset here
```{r}
library(tidyr)
head(GAMES, n=20)

GAMES_CLEANING = data.frame(GAMES[,-3])
head(GAMES_CLEANING, n=20)

GAMES = GAMES_CLEANING %>%
  separate(GAME_DATE_EST, sep="-", into = c("GAME_YEAR", "GAME_MONTH", "GAME_DAY"))

head(GAMES)
head(GAMES_DETAILS)
```

I'll work on cleaning the TEAMS dataset here
```{r}
head(TEAMS, n=30)

TEAMS = data.frame(TEAMS[,-c(1,12)])

head(TEAMS, n=30)

TEAMS[3,7] = 17791
TEAMS[13,7] = 19000
TEAMS[15,7] = 20000
TEAMS[17,7] = 19500
TEAMS[18,7] = 18422

head(TEAMS, n=30)
```


```{r}
#Taking out rows in Comment column that have characters in them.

GAMES_DETAILS<-subset(GAMES_DETAILS, is.na(nchar(GAMES_DETAILS$COMMENT)))
head(GAMES_DETAILS)


#Adding a B(Bench) for empty entries under the Start Position column.

GAMES_DETAILS$START_POSITION[GAMES_DETAILS$START_POSITION==""] <- NA
GAMES_DETAILS$START_POSITION[is.na(GAMES_DETAILS$START_POSITION)] = 'B'



#Changing the minutes in the minute column to seconds.

mmss_to_ss <- function  (string)
{
  mmss <- strsplit (string, ":", T)
  mm <- as.numeric (mmss[[1]][1])
  ss <- as.numeric (mmss[[1]][2])
  return (mm * 60 + ss)
}

temp<- GAMES_DETAILS[9]
new1<- apply(temp, 1, mmss_to_ss)
new1<- as.data.frame(new1)
GAMES_DETAILS$MIN1 <- new1$new1
GAMES_DETAILS<- subset(GAMES_DETAILS, select = -MIN )
names(GAMES_DETAILS)[28] <- "SEC"

head(GAMES_DETAILS)
```


Below is the chunk of code that Mario gave us in class, changed a little bit so that it is for all of the games in the dataset
```{r}
#Preview Datasets
head(GAMES, n=20)
head(GAMES_DETAILS, n=20)
head(TEAMS)


#Simplify Games Data
ALL_GAMES=GAMES %>%
            select(GAME_YEAR, GAME_MONTH, GAME_DAY,GAME_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,PTS_home,PTS_away) %>%
            mutate(Spread=PTS_home-PTS_away,Total=PTS_home+PTS_away)
head(ALL_GAMES)

#Obtain Aggregated OREB from Player Level Statistics
OREB = GAMES_DETAILS %>%
          select (TEAM_ABBREVIATION,GAME_ID,TEAM_ID,OREB) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(OREB=sum(OREB,na.rm=T)) %>%
          ungroup()
#Obtain Aggregated DREB from Player Level Statistics
DREB = GAMES_DETAILS %>%
          select (TEAM_ABBREVIATION,GAME_ID,TEAM_ID,DREB) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(DREB=sum(DREB,na.rm=T)) %>%
          ungroup()
#Obtain Aggregated REB from Player Level Statistics
REB = GAMES_DETAILS %>%
          select (TEAM_ABBREVIATION,GAME_ID,TEAM_ID,REB) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(REB=sum(REB,na.rm=T)) %>%
          ungroup()
#Obtain Aggregated AST from Player Level Statistics
AST = GAMES_DETAILS %>%
          select (TEAM_ABBREVIATION,GAME_ID,TEAM_ID,AST) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(AST=sum(AST,na.rm=T)) %>%
          ungroup()
#Obtain Aggregated STL from Player Level Statistics
STL = GAMES_DETAILS %>%
          select (TEAM_ABBREVIATION,GAME_ID,TEAM_ID,STL) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(STL=sum(STL,na.rm=T)) %>%
          ungroup()
#Obtain Aggregated BLK from Player Level Statistics
BLK = GAMES_DETAILS %>%
          select (TEAM_ABBREVIATION,GAME_ID,TEAM_ID,BLK) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(BLK=sum(BLK,na.rm=T)) %>%
          ungroup()
#Obtain Aggregated TO from Player Level Statistics
TO = GAMES_DETAILS %>%
          select (TEAM_ABBREVIATION,GAME_ID,TEAM_ID,TO) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(TO=sum(TO,na.rm=T)) %>%
          ungroup()
#Merging These Stats Into Game Data
ALL_GAMES_DONE_1 = left_join(ALL_GAMES,select(OREB,-TEAM_ABBREVIATION),by=c("GAME_ID","HOME_TEAM_ID"="TEAM_ID")) %>%
                    rename(OREB_home=OREB) %>%
                    left_join(select(OREB,-TEAM_ABBREVIATION),by=c("GAME_ID","VISITOR_TEAM_ID"="TEAM_ID")) %>%
                    rename(OREB_away=OREB) %>%
                    mutate(OREB=OREB_home+OREB_away)
ALL_GAMES_DONE_2 = left_join(ALL_GAMES_DONE_1,select(DREB,-TEAM_ABBREVIATION),by=c("GAME_ID","HOME_TEAM_ID"="TEAM_ID"))
ALL_GAMES_DONE_3 = left_join(ALL_GAMES_DONE_2,select(REB,-TEAM_ABBREVIATION),by=c("GAME_ID","HOME_TEAM_ID"="TEAM_ID"))
ALL_GAMES_DONE_4 = left_join(ALL_GAMES_DONE_3,select(AST,-TEAM_ABBREVIATION),by=c("GAME_ID","HOME_TEAM_ID"="TEAM_ID"))
ALL_GAMES_DONE_5 = left_join(ALL_GAMES_DONE_4,select(STL,-TEAM_ABBREVIATION),by=c("GAME_ID","HOME_TEAM_ID"="TEAM_ID"))
ALL_GAMES_DONE_6 = left_join(ALL_GAMES_DONE_5,select(BLK,-TEAM_ABBREVIATION),by=c("GAME_ID","HOME_TEAM_ID"="TEAM_ID"))
ALL_GAMES_DONE_7 = left_join(ALL_GAMES_DONE_6,select(TO,-TEAM_ABBREVIATION),by=c("GAME_ID","HOME_TEAM_ID"="TEAM_ID"))
  
head(ALL_GAMES_DONE_7)
#Creating Home Team and Away Team Variables
ALL_TEAMS= TEAMS %>%
            select(TEAM_ID,CITY,NICKNAME) %>%
            unite(NAME,CITY,NICKNAME,sep=" ")
head(ALL_TEAMS)
#Merging Team Name into original data
ALL_GAMES_DONE_AGAIN=left_join(ALL_GAMES_DONE_7,ALL_TEAMS,by=c("HOME_TEAM_ID"="TEAM_ID")) %>%
                        rename("Home Team"=NAME) %>%
                        left_join(ALL_TEAMS,by=c("VISITOR_TEAM_ID"="TEAM_ID")) %>%
                        rename("Away Team"=NAME) %>%
                        select("Home Team","Away Team",everything()) %>%
                        select(-GAME_ID,-HOME_TEAM_ID,-VISITOR_TEAM_ID)

head(ALL_GAMES_DONE_AGAIN)
```

```{r}
head(NBA_STATS_ADVANCED_20_21)
```


